# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coding Militia
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Code, headbang, grouch, repeat!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.codingmilitia.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus:
  shortname: codingmilitia
# author: joaofbantunes
twitter_username: joaofbantunes

# social_sites:
#   twitter: joaofbantunes
#   github:  joaofbantunes

# rss: rss

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-youtube
  - jekyll-archives
  - jekyll-paginate
  - jekyll-gist

paginate: 10
  

permalink: /:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
    - categories
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: category-tag-archive-layout
    category: category-tag-archive-layout
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

google_analytics: UA-58690226-4

title_image: '/assets/logo.jpg'