# Annoy the bots
[[redirects]]
from = "/h/*"
to = "https://www.youtube.com/watch?v=082C6EdNvus"
status = 302

# Redirect domain aliases to primary domain
[[redirects]]
from = "https://www.blog.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true