[context.production.environment]
    HUGO_ENV = "production"

# Annoy the bots
[[redirects]]
from = "/h/*"
to = "https://www.youtube.com/watch?v=082C6EdNvus"
status = 302
force = true

# Plausible proxy - https://plausible.io/docs/proxy/introduction & https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/p/js/script.js"
to = "https://plausible.io/js/script.js"
status = 200
force = true

# Plausible proxy - https://plausible.io/docs/proxy/introduction & https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/p/api/event"
to = "https://plausible.io/api/event"
status = 200
force = true

# youtube shortcut
[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/c/CodingMilitia"
status = 302
force = true

# twitch shortcut
[[redirects]]
from = "/twitch"
to = "https://twitch.tv/joaofbantunes"
status = 302
force = true

# linkedin shortcut
[[redirects]]
from = "/linkedin"
to = "https://linkedin.com/in/joaofbantunes"
status = 302
force = true

# bluesky shortcut
[[redirects]]
from = "/bsky"
to = "https://bsky.app/profile/joao.antunes.dev"
status = 302
force = true

# dev.to shortcut
[[redirects]]
from = "/dev.to"
to = "https://dev.to/joaofbantunes"
status = 302
force = true

# Redirect categories and tags
[[redirects]]
from = "https://blog.codingmilitia.com/category/*"
to = "https://blog.codingmilitia.com/categories/:splat"
status = 301
force = true

[[redirects]]
from = "https://blog.codingmilitia.com/tag/*"
to = "https://blog.codingmilitia.com/tags/:splat"
status = 301
force = true

[[redirects]]
from = "https://codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

# Redirect domain aliases to primary domain
[[redirects]]
from = "https://www.blog.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"