# Annoy the bots
[[redirects]]
from = "/h/*"
to = "https://www.youtube.com/watch?v=082C6EdNvus"
status = 302

# youtube shortcut
[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/c/CodingMilitia"
status = 302

# twitch shortcut
[[redirects]]
from = "/twitch"
to = "https://twitch.tv/joaofbantunes"
status = 302

# twitter shortcut
[[redirects]]
from = "/twitter"
to = "https://twitter.com/joaofbantunes"
status = 302

# linkedin shortcut
[[redirects]]
from = "/twitch"
to = "https://linkedin.com/in/joaofbantunes"
status = 302

# dev.to shortcut
[[redirects]]
from = "/dev.to"
to = "https://dev.to/joaofbantunes"
status = 302

# Redirect domain aliases to primary domain
[[redirects]]
from = "https://www.blog.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.codingmilitia.com/*"
to = "https://blog.codingmilitia.com/:splat"
status = 301
force = true